# Step 1: Create a 3x3 identity matrix called "m1"

In [1]:
import tensorflow as tf
m1 = tf.eye(3)

print(m1.numpy())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Step 2: Create a vector  called "v1" with values ranging from 0 to 8

In [2]:
v1 = tf.constant(list(range(9)), dtype=tf.float32)
print(v1.numpy())

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


# Step 3: Reshape v1 to 3\*3 matrix called m2 

In [3]:
m2 = tf.reshape(v1, [3,3])

print(m2.numpy())

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


# Step 4: Calculate element-wise multiply on m1 and m2

In [4]:
ele_mul = m1 * m2
print(ele_mul)

tf.Tensor(
[[0. 0. 0.]
 [0. 4. 0.]
 [0. 0. 8.]], shape=(3, 3), dtype=float32)


# Step 5: Add 3 on each of m1 element (called m3) 

In [5]:
m3 = m1 + 3
print(m3.numpy())

[[4. 3. 3.]
 [3. 4. 3.]
 [3. 3. 4.]]


# Step 6: Calculate m3\*m2 where * is matrix multipy  

In [6]:
max_mul = tf.linalg.matmul(m3,m2)
print(max_mul.numpy())

[[27. 37. 47.]
 [30. 40. 50.]
 [33. 43. 53.]]


# Step 7: sum all of m2 value

In [7]:
m2_sum = tf.math.reduce_sum(m2)
print(m2_sum.numpy())

36.0


# Step 8: sum all column vector on m2 matrix

In [8]:
m2_t = tf.linalg.matrix_transpose(m2)
sum_vector = m2_t[0] + m2_t[1] + m2_t[2]  
print(sum_vector.numpy())

[ 3. 12. 21.]
